# Generated by Django 4.2.1 on 2024-02-03 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IDCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField(default=0)),
                ('workflow_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('workflow_id', models.IntegerField()),
                ('task_performance_time', models.DateTimeField()),
                ('workflow_submission_time', models.DateTimeField()),
                ('workflow_type', models.CharField(max_length=255)),
                ('workflow_name', models.CharField(max_length=255)),
                ('samples', models.IntegerField()),
                ('status', models.CharField(max_length=255)),
                ('last_status', models.CharField(blank=True, max_length=255, null=True)),
                ('sample_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Workflow_name', models.CharField(max_length=255)),
                ('Configuration', models.CharField(max_length=255)),
                ('Samples', models.IntegerField()),
                ('Creation', models.DateTimeField()),
                ('Status', models.CharField(max_length=50)),
                ('Workflow_ID', models.CharField(max_length=10)),
                ('sample_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowFileData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_content', models.TextField()),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geneapp.userhistory')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('institute_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userhistory',
            name='file_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Geneapp.workflowfiledata'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Geneapp.userprofile'),
        ),
    ]
