# Generated by Django 5.0 on 2024-05-03 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Geneapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhistory',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='idcounter',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='userhistory',
            name='project_id',
        ),
        migrations.AddField(
            model_name='userhistory',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Geneapp.project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userhistory',
            name='reference_genome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workflow',
            name='reference_genome',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WorkflowFileData',
        ),
    ]
